### ISSUE TITLE
是否开启了core dump功能，导致磁盘空间被占满

### ISSUE THREAD

**Issue by 0xcrAne** [TideSec/Mars#10]
是否开启了core dump功能?添加了一些资产，第二天30G的磁盘被占满，查看发现/Tide-Mars/taskpython/目录下有大量core文件，最大每个50M，查看ulimit -c命令发现是ulimited状态。是不是代码写了此功能，而且没做限制。

**Comment by TideSec** [comment]
我这暂时没遇到过这个问题，我再多测试一下看看~谢谢反馈~
