### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by MarkHappyShao** [TideSec/Mars#11]
1、服务器重启，服务永远要自己进入docker手动启动
2、资产添加，扫描的话，任务永远都是排队中，需要自己后台手动启动扫描脚本才行，每次启动任务都要，麻烦死了。
3、T填IP的话，永远扫不出目标的端口出来，永远只出一个IP就完事了。
4、填写单个IP，如果你之前选过C段的话，以后永远都是扫C段了，不能扫单IP了

**Comment by TideSec** [comment]
1和2问题已经修复，docker已经重新部署。
3和4是之前没考虑单个ip的问题，下个版本会改进~
