### ISSUE TITLE
容器时区有问题

### ISSUE THREAD

**Issue by 0xzmz** [TideSec/Mars#2]
### 经测试使用，发现容器中时区有问题，不是上海的，建议参考下面文章修改

[https://www.cnblogs.com/QuLory/archive/2013/03/24/2978366.html](https://www.cnblogs.com/QuLory/archive/2013/03/24/2978366.html)

**Comment by TideSec** [comment]
好的，非常感谢，当时没注意这个问题，下个版本会修复的。
