### ISSUE TITLE
建议扫描端和WEB分离，做成可分布式

### ISSUE THREAD

**Issue by 0xss** [TideSec/Mars#3]

**Comment by TideSec** [comment]
Mars支持分布式扫描，之前忘了在readme里面写，现在已经补充上了。

Mars支持分布式部署，可以多节点同时扫描，空闲节点会优先执行任务，节点任务相互没有干扰。

- 在web控制台添加多个任务；
- 每个节点接收任务后会把该任务进行标记，这样其他节点不会重复扫描；
- 如果某节点因为出错而导致没有完成扫描，下次该节点再次启动时会继续执行该任务；
- 节点的标识是靠`taskpython/asset_task_scan_v1.0.py`文件中的`scan_node`参数，默认是主机名，可自行修改。

**多节点的部署方式：**
- 1、把`taskpython`目录拷贝到其他服务器上。
- 2、安装依赖包`pip install -r requirements.txt`
- 3、修改`asset_task_scan_v1.0.py`文件中的`MONGODB_CONFIG`的mongo数据库地址。
- 4、运行`python asset_task_scan_v1.0.py`即可。
