### ISSUE TITLE
awvs扫描报错，由于目标没有响应，因此无法确定威胁级别

### ISSUE THREAD

**Issue by skr-rks** [TideSec/Mars#30]
awvs服务已起。进docker环境确认过了

**Comment by skr-rks** [comment]
已调用其他机器awvs进行扫描

**Comment by Crazy-FuQing** [comment]
楼书你好 请问你的问题解决了吗  我也遇到了相同的问题  特来求解

![image](https://user-images.githubusercontent.com/46838021/102572259-8b814680-4126-11eb-8e51-0f5ce70550d5.png)

**Comment by skr-rks** [comment]
> 楼书你好请问你的问题解决了吗我也遇到了相同的问题特来转化
> 
> ![图片](https://user-images.githubusercontent.com/46838021/102572259-8b814680-4126-11eb-8e51-0f5ce70550d5.png)

没有，后来使用单独的awvs就可以了。内置的Unstable

**Comment by Crazy-FuQing** [comment]
了解，感谢
