### ISSUE TITLE
启动mars.py的时候报错

### ISSUE THREAD

**Issue by Octopuszz** [TideSec/Mars#5]

**Comment by TideSec** [comment]
什么错误，请附上错误代码或截图

**Comment by Octopuszz** [comment]
mars.py今天启动的时候又没问题了，但是那个启动AWVS的时候出错，无法打开http://ip:13443

![1](https://user-images.githubusercontent.com/41614886/81519668-9e53c180-9374-11ea-9961-1ea3163892d8.PNG)

**Comment by TideSec** [comment]
这个是awvs没启动起来导致的错误，可以登录到容器
```
docker exec tide-mars  /bin/bash
```
执行`ps -aux | grep  acunetix`，查看有没有awvs进程，如果没有的话执行下面的命令：
```
nohup su -l acunetix -c /home/acunetix/.acunetix_trial/start.sh &
```
再次执行`ps -aux | grep  acunetix`，查看有没有awvs进程，如果出现下面内容，说明正常。

![image](https://user-images.githubusercontent.com/46297163/82772482-d75e5c80-9e71-11ea-9a73-b60fc0774e07.png)
