### ISSUE TITLE
打开某些功能时会自动退出登录

### ISSUE THREAD

**Issue by muYoz** [TideSec/Mars#9]
资产管理——资产任务：

127.0.0.1 - - [2020-05-13 14:57:04] "GET /new-customer HTTP/1.1" 200 13776 0.001000
127.0.0.1 - - [2020-05-13 14:57:08] "GET /new-asset HTTP/1.1" 200 15155 0.030000
127.0.0.1 - - [2020-05-13 14:57:14] "GET /asset-management HTTP/1.1" 302 392 0.093000
127.0.0.1 - - [2020-05-13 14:57:14] "GET /login HTTP/1.1" 200 3983 0.001000
'NoneType' object has no attribute '__getitem__'

认证检测——添加扫描：
127.0.0.1 - - [2020-05-13 15:01:20] "GET /new-auth-tester HTTP/1.1" 302 392 0.030000
127.0.0.1 - - [2020-05-13 15:01:20] "GET /login HTTP/1.1" 200 3983 0.000000
'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [2020-05-13 15:01:20] "GET /static/font/css/font-awesome.min.css HTTP/1.1" 404 9028 0.002000

系统设置——高级设置：
'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [2020-05-13 15:02:29] "GET /advanced-option HTTP/1.1" 302 392 0.030000
127.0.0.1 - - [2020-05-13 15:02:29] "GET /login HTTP/1.1" 200 3983 0.001000
127.0.0.1 - - [2020-05-13 15:02:29] "GET /static/font/css/font-awesome.min.css HTTP/1.1" 404 9028 0.003000

看起来是某些地方空值导致？

**Comment by wanggh1021** [comment]
同样出现此问题

**Comment by TideSec** [comment]
测试阶段为了方便，注释掉了登录验证才导致的报错，重新登录一下就可以了。现在最新的代码和docker均已修复该问题。
